version: '2'
services:
    itgm-app:
        image: itgm
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://itgm-mysql:3306/itgm?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    itgm-mysql:
        extends:
            file: mysql.yml
            service: itgm-mysql
